### ISSUE TITLE
Support PHP8.1

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/groupware#27]
### Describe the task

Same as https://github.com/nextcloud/server/issues/29287 but for our components.

### Affected components

* [x] https://github.com/nextcloud/calendar/pull/3996
* [x] https://github.com/nextcloud/calendar_resource_management/pull/46
* [x] https://github.com/nextcloud/contacts/pull/2683
* [x] https://github.com/nextcloud/mail/pull/6131

### To do

* [x] Update info.xml requirements
* [x] Update composer.json requirements
* [x] Update test matrix
* [x] Update lint matrix
* [x] Fix the code

**Comment by ChristophWurst** [comment]
We will support it when the code is ready.

**Comment by darix** [comment]
Do you have any ETA when this will be released?

**Comment by ChristophWurst** [comment]
When the migration is done.
