### ISSUE TITLE
Move non time critical background tasks to maintenance window

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/groupware#28]
### Describe the task

With https://github.com/nextcloud/server/pull/30945 it will be possible to move background jobs to times where the server is less busy. We have some tasks that currently run at a fixed interval, where it might make sense to move them for the chance of yielding better performance. I'm thinking about the calendar resources sync for example.

### Affected components

- [x] Calendar & Contacts backend https://github.com/nextcloud/server/pull/31316
  - [BuildReminderIndexBackgroundJob](https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/BuildReminderIndexBackgroundJob.php)
  - [CalendarRetentionJob](https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/CalendarRetentionJob.php)
  - ~~[CleanupDirectLinksJob](https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/CleanupDirectLinksJob.php)~~
  - ~~[CleanupInvitationTokenJob](https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/CleanupInvitationTokenJob.php)~~
  - ~~[EventReminderJob](https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/EventReminderJob.php)~~
  - [GenerateBirthdayCalendarBackgroundJob](https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/GenerateBirthdayCalendarBackgroundJob.php)
  - [RefreshWebcalJob](https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php)
  - [RegisterRegenerateBirthdayCalendars](https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/RegisterRegenerateBirthdayCalendars.php)
  - ~~[UpdateCalendarResourcesRoomsBackgroundJob](https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/UpdateCalendarResourcesRoomsBackgroundJob.php)~~
  - [UploadCleanup](https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/UploadCleanup.php)
- [x] Calendar https://github.com/nextcloud/calendar/pull/3974
  - [CleanUpOutdatedBookingsJob](https://github.com/nextcloud/calendar/blob/main/lib/BackgroundJob/CleanUpOutdatedBookingsJob.php)
- [x] Contacts https://github.com/nextcloud/contacts/pull/2645
  - [SocialUpdate](https://github.com/nextcloud/contacts/blob/main/lib/Cron/SocialUpdate.php)
  - [SocialUpdateRegistration](https://github.com/nextcloud/contacts/blob/main/lib/Cron/SocialUpdateRegistration.php)
- [x] Mail https://github.com/nextcloud/mail/pull/6053
  - [CleanupJob](https://github.com/nextcloud/mail/blob/main/lib/BackgroundJob/CleanupJob.php)
  - ~~[MigrateImportantJob](https://github.com/nextcloud/mail/blob/main/lib/BackgroundJob/MigrateImportantJob.php)~~
  - ~~[SyncJob](https://github.com/nextcloud/mail/blob/main/lib/BackgroundJob/SyncJob.php)~~
  - [TrainImportanceClassifierJob](https://github.com/nextcloud/mail/blob/main/lib/BackgroundJob/TrainImportanceClassifierJob.php)

### To do

- [x] Find out which of our background jobs are not time critical
- [x] Move them

**Comment by tcitworld** [comment]
I suggested a list of non-important jobs above

**Comment by ChristophWurst** [comment]
not all heroes wear capes

**Comment by nickvergessen** [comment]
Server PR merged
