### ISSUE TITLE
Rename main repo branches

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/groupware#3]
Our repos still use `master` for the main branch and we should finally switch to `main`. Github and other tools should work without any issues by now.

### Possible pain points to check
- [x] CI or other automated processes that assume a default branch name
- [x] backport bot

### Workflow

Follow the instructons on https://github.com/github/renaming/ to get all the nice benefits of auto renaming for open PRs etc.

Then look through all workflows for mentions of the master branch for this repository and rename them to `main`.

You can update your local branches by running:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
### Repos
- [x] https://github.com/nextcloud/calendar/issues/3822
- [x] https://github.com/nextcloud/calendar-js/issues/356
- [x] https://github.com/nextcloud/calendar_resource_management/issues/42
- [x] https://github.com/nextcloud/cdav-library/issues/602
- [x] https://github.com/nextcloud/contacts/issues/2568
- [x] https://github.com/nextcloud/mail/issues/5870

Ref https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/
Ref https://github.com/github/renaming/

**Comment by miaulalala** [comment]
I did the Calendar Resource Management repo in the way github suggests here: https://github.com/github/renaming/ and it worked well. I would recommend doing this the github way to get all those nice benefits of automatically alerting users to the change and so on.

**Comment by st3iny** [comment]
> I did the Calendar Resource Management repo in the way github suggests here: https://github.com/github/renaming/ and it worked well. I would recommend doing this the github way to get all those nice benefits of automatically alerting users to the change and so on.

I agree. That also updates the base branch of all open pull requests automatically.

**Comment by ChristophWurst** [comment]
> Preliminary todo

@miaulalala please update this with the steps we now do for every repo.

As the renaming of the resources repo didn't create any trouble so far I would say we migrate all other repos as soon as possible.

**Comment by miaulalala** [comment]
Workflow:

Follow the instructons on https://github.com/github/renaming/ to get all the nice benefits of auto renaming for open PRs etc.

Then look through all workflows for mentions of the master branch for this repository and rename them to `main`.

You can update your local branches by running:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by miaulalala** [comment]
All done
