### ISSUE TITLE
Migrate to material icons

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/groupware#38]
### Describe the task

Nextcloud 25 has a hard breaking change and we need to change our icons for it https://github.com/nextcloud/server/issues/32060

### Affected components

* [x] Calendar
* [x] Contacts
* [x] Mail
* [x] ~~``@nextcloud/calendar-availability-vue``~~ -> not time critical https://github.com/nextcloud/calendar-availability-vue/issues/28

### To do

- [x] Replace all icons
- [x] Schedule a review meeting for each app to fine-tune the icon choice
- [x] Requires a release of https://github.com/nextcloud/nextcloud-vue/pull/2727

**Comment by ChristophWurst** [comment]
How far are we with this migration @GretaD?

**Comment by GretaD** [comment]
> How far are we with this migration @GretaD?

99% for mail, there are only 2 open PRs, i did a general test last week and i think thats all we have to migrate here(one pr is blocked)
On calendar i think its all done, but i havent test it yet like i did with mail to see if i missed smth.
Contacts, i havent started yet.

If you need an ETA, i can finish all this week (but the blocked PR).

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar-availability-vue/blob/main/src/CalendarAvailability.vue also uses two `icon-`* classes that need replacing

**Comment by GretaD** [comment]
_To do on contacts with stoppers:_ 
All the loading icons
Icon-add on - AppNavigationCaption used on RootNavigation.vue no icon slot
Icon-add on AppNavigationNew used on Contacts.vue - no icon slot

_to do but that are leftovers, and will be done in one pr this week:_
icon external on rootnavigation
icon-checkmark entitysearchresult
icon-group/icon-user line 126 on settingsaddressbookshare
icon-history line 105 and icon-errorr on contactdetails

**Comment by GretaD** [comment]
_To do on contacts, no stoppers_

icon-add on checkavailibility
icon-group/icon-user/icon-circle calendarlistitemsharingsearch
Icon-add on AppNavigationItem used on calendarlistnew
icons on avatarparticipationstatus

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/contacts/issues/2960 misses an icon upgrade.

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-10-10 12-36-16](https://user-images.githubusercontent.com/1374172/194847566-cf71a179-e751-4f1e-8cfe-098f999a05a5.png)
