### ISSUE TITLE
🎄❄️🎅  XMas Wishlist 🎁🦌🌟

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/groupware#4]
Please add tickets here (new or old) that you'd love to fix but have a hard time finding the time for!

**Comment by miaulalala** [comment]
Clean up contacts, for example:

https://github.com/nextcloud/contacts/issues/2502

**Comment by st3iny** [comment]
https://github.com/nextcloud/cdav-library/issues/400

**Comment by st3iny** [comment]
https://github.com/nextcloud/mail/pull/5723

**Comment by ChristophWurst** [comment]
:wave::santa:
