### ISSUE TITLE
Make use of `\OCP\IUserManager::getDisplayName`

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/groupware#53]
### Describe the task

https://github.com/nextcloud/server/issues/33589

### Affected components

Calendar, Calendar Resource Management, Contacts, Mail

### To do

- [x] Find out where we fetch a user object just for the display name
- [x] Replace all occurences

**Comment by hamza221** [comment]
I think this is done

**Comment by hamza221** [comment]
GetDisplayName is not used in Calendar Resource Management and Contacts

**Comment by ChristophWurst** [comment]
Awesome!
