### ISSUE TITLE
App ownership and release management training

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/groupware#6]
All apps are currently in the hand of one person. To spread the knowledge about app ownership and releases processes, we should distribute responsibilities across the team.

Ideally each of us takes at least one app, so the processes are familiar. If another team member is unavailable this should give the possibility to take over the app temporarily.

- [x] https://github.com/nextcloud/documentation/pull/7822
- [x] Assign maintainers to our apps, the whole team acts as backup
  + [x] Contacts: @ChristophWurst 
  + [x] Calendar: @miaulalala
  + [x] Calendar Resource Management: @st3iny 
  + [x] Mail: @GretaD
  + [x] Customer app(s): @miaulalala 
- [x] Make sure keys are available to everyone
- [x] Do a release together
- [x] Do an assisted release together
- [x] Document the process in this repo (as long as there is no general doc for this readily available)
- [x] ~~Update app repos pointing to the process (for us but also others to understand how things are done)~~ hard to find the right place for this

**Comment by tcitworld** [comment]
Also edit and update the `<author>` fields in `appinfo/info.xml`.

**Comment by ChristophWurst** [comment]
> Document the process in this repo (as long as there is no general doc for this readily available)

@GretaD could you please add a `processes/app_release.md` file to this repo with your guide? :)

**Comment by GretaD** [comment]
> > Document the process in this repo (as long as there is no general doc for this readily available)
> 
> @GretaD could you please add a `processes/app_release.md` file to this repo with your guide? :)

which process, the commands for the release we did yesterday?

**Comment by ChristophWurst** [comment]
yes

**Comment by tcitworld** [comment]
There doesn't seem to be a list of current groupware members anywhere, should it be a Github team?

**Comment by ChristophWurst** [comment]
I'm planning to update the readme to look like https://github.com/nextcloud/wg-two-factor-authentication#members

We could use a github team, the only think that makes me hesitant is that 600 people in our orga will be able to randomly ping the whole group and this has caused notification spam that we saw with other teams.
