### ISSUE TITLE
Try renovate bot for npm dependencies

### ISSUE THREAD

**Issue by kesselb** [nextcloud/groupware#63]
### Describe the task

Renovate bot supports package grouping: https://docs.renovatebot.com/noise-reduction/#package-grouping

Especially mail and ckeditor would benefit from package grouping.

- https://github.com/nextcloud/collectives/pull/483
- https://github.com/nextcloud/collectives/blob/main/renovate.json
- https://github.com/nextcloud/text/pull/3558
- https://github.com/nextcloud/text/blob/master/renovate.json#L52-L58

### Affected components

Mail

### To do

- [ ] Evaluate renovate bot

**Comment by st3iny** [comment]
Great idea! We could use it for vue, jest, fullcalendar and ckeditor.

**Comment by ChristophWurst** [comment]
The other aspect of renovate is to have semantical bumps for https://github.com/nextcloud/groupware/issues/60. The current shortcoming of Dependabot is that it always uses the same prefix. But I would like to use `chore` for dev deps and `fix` for patch updates of production deps.

**Comment by ChristophWurst** [comment]
> semantical bumps

That works super well: https://github.com/ChristophWurst/nextcloud_sentry/pull/498

**Comment by ChristophWurst** [comment]
I would say the setup in Mail looks good now.

The only minor annoyance is the commit/PR title. It's long and doesn't tell us the previous version.

E.g. ``fix(deps): update dependency sabberworm/php-css-parser to ^8.4.0 (main)``

I'd prefer the Dependabot-style title ``fix(deps): bump sabberworm/php-css-parser from 8.3  to 8.4.0``

**Comment by ChristophWurst** [comment]
It's in place for Mail and works well. We can expand to other repos as our time allows.
